### ISSUE TITLE
[Suggestion] about.html takes the info from the Json file

### ISSUE THREAD

**Issue by rubereaglenest** [erkyrath/lectrote#100]
Hi, I wonder if it is possible to have the about.html for bound games automatically getting the info from the json file. I don't know if this is a silly thing to ask, because I really have no idea of web development. But if possible, it could me less to have to enter that info twice, and have to manually set all those ??? number versions in the about.html file.

Regards.

Ruber.

**Comment by rubereaglenest** [comment]
Also, an idea, an option where the packager extract all the meta info from blorb files.

**Comment by erkyrath** [comment]
Which information are you not seeing? The standard Lectrote about.html pulls information about all that information when it loads. If you copy that and then modify it for your bound game, it should still work.

(Except for interpreters which are excluded by the lectroteSoleInterpreter key. You should remove mention of those from the about.html file, since the point is that you're not shipping those interpreters.)

Pulling metadata from the blorb is a nice idea, but I'm not sure how much work it would save. You still have to customize the package.json file in various ways.

**Comment by rubereaglenest** [comment]
ah, sorry. I thought that the readme says that we must edit the about.html by hand, and got that literally.

Well, let me see if I can successfully package the game, and then we'll see. I mean, the packaging is still failing for me so I'm not seeing any information yet.

**Comment by curiousdannii** [comment]
It wouldn't be hard for about.html to, instead of replacing the question marks with the version numbers, to add the whole text. Each VM could be added only if its package.json/versions.json file is present.
