### ISSUE TITLE
Request for much longer scrollback

### ISSUE THREAD

**Issue by aubloom** [erkyrath/lectrote#132]
Feature request: Could you increase the history/scrollback size?

I know it can't be infinite, because I asked about it years ago in this topic on intfiction:
https://intfiction.org/t/lectrote-1-1-0-now-with-ink-support/10247/4

But could(n't) it just be a whole lot longer than it is now? I mean, way longer! Thanks.

**Comment by erkyrath** [comment]
There is a limit where the scrollback starts to make the browser engine lag. As that thread says, I haven't done research to find where it might be.

There's probably also a UI limit where you can't scan around effectively because dragging the scroll bar is too extreme. That would be pretty big, though.

**Comment by aubloom** [comment]
Thanks. That's already a big improvement on where it was.
