### ISSUE TITLE
TADS 2 status window goes blank at non-100% browser zoom

### ISSUE THREAD

**Issue by erkyrath** [erkyrath/lectrote#133]
Noted on Worlds Apart.

https://intfiction.org/t/lectrote-1-4-0/50036

**Comment by curiousdannii** [comment]
Could the measurements be breaking perhaps?

**Comment by erkyrath** [comment]
Possibly related: the width measurement of the input line also gets messed up at non-100% zoom.

https://intfiction.org/t/lectrote-1-4-0/50036

**Comment by curiousdannii** [comment]
Assuming that it's the same as for Parchment, it looks like the `inset` value that GlkOte calculates is often incorrect when zoomed.

First lets remember that in a modern browser, zooming changes the devicePixelRatio, as if you were using a hiDPI screen. This means that calculations using pixels should still work and keep the same ratios. Because in browsers CSS pixels never actually refer to true device pixels any more.

As you zoom in or out, the padding on the status window remains at 6px top and bottom. The internal dimensions are then what's left over from the `inset` height. For default styles it wants 18px. But when you zoom in or out, it could change, to 15.035, 18.008, 9.021, 14.020, 16, etc. The status window text will only be shown when it is exactly 18px. Oddly even when it went to 18.008 it did not.

**Comment by dfabulich** [comment]
I spent a few minutes today attempting to debug this in Parchment. In `accept_windowset` I see that `arg.gridheight` is 0 when zoomed in and `arg.gridheight` is 1 when unzoomed, which kinda explains the problem, but `arg.gridheight` is coming out of a magical WASM buffer that I can't figure out how to trace.

Where is the magic happening here??

**Comment by curiousdannii** [comment]
Hmm, that suggests the metrics are being recalculated wrongly.

**Comment by dfabulich** [comment]
Well, measure_window seems to generate basically cromulent answers, but I can’t figure out who’s supposed to use that data to compute gridheight…

**Comment by dfabulich** [comment]
I think rounding up fixes this in both forks of glkote.

**Comment by curiousdannii** [comment]
I'm still confused as to how the measurements become different purely by zooming.

**Comment by dfabulich** [comment]
I'm hazy on the details, but I believe browsers adjust text size when zooming, and that `text-size-adjust` has something to do with it. https://developer.mozilla.org/en-US/docs/Web/CSS/text-size-adjust

**Comment by erkyrath** [comment]
Fixed in GlkOte, I hope.

**Comment by curiousdannii** [comment]
I see that AsyncGlk has the same problem.

So the issue only presents itself with TADS. The solution above is to round the metrics, so I'm wondering if the issue is that Remglk can't handle non-integer metrics, but GlkApi can.

Metrics at 110% zoom:

buffercharheight: 20.99431610107422
buffercharwidth: 8
buffermarginx: 10.474400000000003
buffermarginy: 0
graphicsmarginx: 0
graphicsmarginy: 0
gridcharheight: 17.997159957885742
gridcharwidth: 8.4002125
gridmarginx: 20
gridmarginy: 11.988599999999998
height: 324.545
width: 900

It also has the weird situation that RemGlk is sending a 0 height grid window, when I thought it should not send it in that situation?

Should AsyncGlk also round the metrics, or would it be possible to make RemGlk handle non-integer metrics? These height metrics are almost round numbers, but the character widths are definite fractions, and really should be used rather than rounding up. Well @erkyrath must have realised that, because the character metrics are stored as floats:

```
struct data_metrics_struct {
    glui32 width, height;
    glui32 outspacingx, outspacingy;
    glui32 inspacingx, inspacingy;
    double gridcharwidth, gridcharheight;
    glui32 gridmarginx, gridmarginy;
    double buffercharwidth, buffercharheight;
    glui32 buffermarginx, buffermarginy;
    glui32 graphicsmarginx, graphicsmarginy;
};
```

So is the issue that the margins and window sizes are integers? Hmm, but I still can't work out what calculations would lead it to in this situation, with a one line grid window, then set the buffer window height to 298px.

And the metrics for 125% zoom:

buffercharheight: 21.000001907348633
buffercharwidth: 8
buffermarginx: 10.075000000000003
buffermarginy: 0
gridcharheight: 18.000001907348633
gridcharwidth: 8.4
gridmarginx: 20
gridmarginy: 12
height: 285.6
width: 900

I think simply rounding up is not the ideal solution, because then these measurements will be almost 1px too high.

Any thoughts @erkyrath?

**Comment by erkyrath** [comment]
Now that I look at RemGlk, it *should* accept non-integer metrics.

    metrics->gridcharheight = data_raw_real_value(dat);

Can you tell why it isn't?

**Comment by curiousdannii** [comment]
But only for the charheight/width. So it's probably flooring the height and marginy metrics.

**Comment by curiousdannii** [comment]
It wasn't too hard to get RemGlk to use doubles throughout, which I think is probably the better solution than rounding up.

See the PR above.

**Comment by erkyrath** [comment]
Agreed.

**Comment by erkyrath** [comment]
Should be fixed with the next TADS/etc interpreter updates.
