### ISSUE TITLE
Adding Z-Code support

### ISSUE THREAD

**Issue by curiousdannii** [erkyrath/lectrote#70]
I saw [Zarf's comment](http://www.intfiction.org/forum/viewtopic.php?f=7&t=20520#p112701) and thought I'd write a few notes because I'm about to go away for a few days. This will be so much easier once I adapt ZVM to use Glk, but that's not going to happen before IFComp! But for a very crude minimal embedding of Parchment you should only need to intercept these few places:

- Skip loading the story file here and just load the VM files (or maybe just hardcode them in the html?): https://github.com/curiousdannii/parchment/blob/bc793329904fcd7ee0322b517d04de954c289250/src/parchment/library.js#L322
- Load the story here (synchronously if you can with Node?): https://github.com/curiousdannii/parchment/blob/bc793329904fcd7ee0322b517d04de954c289250/src/parchment/library.js#L49
- To handle saving and restoring you'll want to intercept here: https://github.com/curiousdannii/parchment/blob/bc793329904fcd7ee0322b517d04de954c289250/src/parchment/library.js#L401

**Comment by erkyrath** [comment]
Thanks! I intend to look at this over the weekend. (Which is not quite soon enough for IFComp early risers, but we gotta manage real life.)

The big hole is going to be autosave. Adding autosave to Quixe was a big chunk of the original Lectrote development -- it wasn't a weekend task. So the first cut at Parchment integration is just not going to have that.

**Comment by curiousdannii** [comment]
Just remembered that the saving/restoring probably won't work properly with the current ZVM. So use the code from the gh-pages branch (commit f458c458).

**Comment by erkyrath** [comment]
I have created a branch https://github.com/erkyrath/parchment/tree/lectrote (forked from https://github.com/curiousdannii/parchment/tree/gh-pages) which contains the changes I've made so far.

This is all hasty work, so don't just merge it wholesale. Some of the changes should probably be handled differently.

- src/parchment/library.js: I pass the storyfile data in as an array of bytes rather than a URL. So I added a test here for that. If the storyfile is an array, we jump straight to launch_callback() with no AJAX calls or file loads. (zvm.debug.js is already loaded, that's hardwired into Lectrote's zplay.html.)

Maybe this should be more general. The storyfile argument could specify the parchment.vms name in some way. 

- src/parchment/outro.js: I modified this code to be a function rather than executing at JS-load time. The function is called by Lectrote's own JS code when the game is ready to launch.

Now that I look at this, it makes more sense to drop intro.js and outro.js entirely. None of intro.js is relevant to Lectrote, and the outro code could be moved into Lectrote's JS file. So what I should do is just add a new Grunt target that excludes those two files.

- src/structio/api.js: I made a small change, adding class="BufferWindow" to the #main div. This allows Lectrote to apply its font preference. But this is kind of gross, right? I should adjust Lectrote to apply its font to #main directly.

- src/structio/input.js: I added a condition, basically saying that any element with class="CanHaveInputFocus" is excluded from focus-grabbing, like INPUT elements. This turns out to be necessary for the way Lectrote's search widget is set up. (I had to make a similar change in GlkOte.)

**Comment by erkyrath** [comment]
Obviously, I haven't looked at save/restore support at all. Will get to that tomorrow.

**Comment by erkyrath** [comment]
Okay, I've cleaned up.

The current additions to my lectrote branch (as compared to https://github.com/curiousdannii/parchment/tree/gh-pages) are:

- Extended Gruntfile.js to create parchment-bare.debug.js and parchment-bare.min.js, which are the same as parchment.*.js except that intro.js and outro.js are omitted.
- Accept an array as a storyfile in src/parchment/library.js.
- The CanHaveInputFocus change in src/structio/input.js.

I added save/restore support by replacing the library.fromRunner() method after I create the library object. See zplay.js.

**Comment by curiousdannii** [comment]
Good to see this you got this worked out fairly quickly! Are you expecting to keep zcode support in for some time? If so then I'll take a look about merging in some of your commits.

> The one thing I'm missing is the ability to return "save failed", for the save event. (This occurs if the user cancels the save dialog.)

Pass the event object back but add a property 'result' set to 0.

**Comment by erkyrath** [comment]
Yes, merging the current branch would be good.

Feel free to come up with a cleaner way to signal that the storyfile is an already-loaded game file, and that the VM is already loaded. (These could be independent options.)

> Pass the event object back but add a property 'result' set to 0

I am trying this but it doesn't work.

	if (!fref) {
		/* Save dialog cancelled. Mark event as having failed. */
		event.result = 0;
		console.log('### failed', event);
	}
	//...
	runner.fromParchment( event );

A cancelled SAVE still says "Ok." in the game output.

**Comment by curiousdannii** [comment]
Oh, I made a dumb error. I'm simply ORing the result with 1, which means you can't pass in 0. In zvm.debug.js try replacing with this line: (line 3422)

```
			this.variable( data.storer, data.result === undefined ? 1 : data.result );
```

I'll fix this in ZVM, but probably not immediately because I'm in the process of adding Z3 support, which is ending up being rather tricky. So you're probably best hand editing the lib files for now. I'll post back here when it's stable again. (Or send a pull request.)

**Comment by erkyrath** [comment]
That worked, thanks!

I am putting this task down as "done" for the moment. Let me know when Parchment reaches a new stable point and I will update Lectrote again.
